### ISSUE TITLE
Support for .vstpreset files

### ISSUE THREAD

**Issue by wrenchse** [CrushedPixel/Plugalyzer#13]
I think Plugalyzer could be even more useful if we could load vstpresets directly.
From what I found it seems pretty straightforward; I'd give it a go myself but haven't worked with JUCE before at all. 
https://forum.juce.com/t/loading-vstpresets-in-vst3-plugins-do-not-load-correctly/47111/2

PS. I love this tool, super well made!

**Comment by CrushedPixel** [comment]
This definitely seems like a good addition.

**Comment by CrushedPixel** [comment]
See #18 - please test and report back!

**Comment by CrushedPixel** [comment]
@steveschow is this what you need (vstpreset support)? If so, please test and let me know if it works!

**Comment by steveschow** [comment]
I have built a version of Plugalyzer that can support VST2, since I have the VST2 sdk. 

Using that I am able to test out the freely available Piz midi plugins.  However, they do not work at all in Plugalyzer due to bus layout conflict of some kind.  See results below.  At this point I am running out of time to continue further testing and trying Plugalyzer.  I will watch the updates, when its released with VSTpreset, midi plugin and deals with whatever it needs to deal with so that I can test midi plugins (preferably also VST2) then I will try it again.  good luck.


```
 ./Plugalyzer process --plugin=/Library/Audio/Plug-Ins/VST/piz/midiNotesToCC.vst --midiInput=/Users/sjs/Desktop/testmidi.mid --midiOutput=/Users/sjs/Desktop/output.mid
Attempting to load VST: /Library/Audio/Plug-Ins/VST/piz/midiNotesToCC.vst
Creating VST instance: midiNotesToCC
Initialising VST: midiNotesToCC (1.1.0.0)
Attempting to load VST: /Library/Audio/Plug-Ins/VST/piz/midiNotesToCC.vst
Creating VST instance: midiNotesToCC
Initialising VST: midiNotesToCC (1.1.0.0)
Plugin does not support requested bus layout
```
